[package]
name = "chat"
version = "1.0.0"
authors = []

[addresses]
chat_addr = "_"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
std = "0x1"

[dev-dependencies]
